version: "3.7"
services:
  pgadmin4:
    image: dpage/pgadmin4:latest
    networks:
      - network_public
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=leonardo@ventros.com.br
      - PGADMIN_DEFAULT_PASSWORD=Theta6465
      - PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION=True
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
          # - node.hostname == worker1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.pgadmin4.rule=Host(`pgadmin.leonardocaloi.com.br`)"
        - "traefik.http.routers.pgadmin4.entrypoints=websecure"
        - "traefik.http.routers.pgadmin4.priority=1"
        - "traefik.http.routers.pgadmin4.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.pgadmin4.loadbalancer.server.port=80"
        - "traefik.http.routers.pgadmin4.service=pgadmin4"
      resources:
        limits:
          cpus: "1"
          memory: 1024M

volumes:
  pgadmin_data:
    external: true
    name: pgadmin_data

networks:
  network_public:
    external: true
    name: network_public
